packages:
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  x-data-spreadsheet: true

packageExtensions:
  '@analogjs/vite-plugin-angular':
    dependencies:
      typescript: '~5.8.3'

